[package]
name = "chat-server"
version.workspace = true
edition.workspace = true

[dependencies]
protocol = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
